name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: configure CMake
      run: cmake -B build
    
    - name: build
      working-directory: build
      run: make
    
    - name: run tests
      working-directory: build
      run: ctest -V
      
